# Generated by Django 2.2 on 2021-06-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentarr',
            new_name='StudentGrade',
        ),
    ]
